# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# jobs:
#   build:

#     runs-on: macos-latest

#     steps:
#     - uses: maxim-lobanov/setup-xcode@v1
#       with:
#         xcode-version: latest
#     - uses: actions/checkout@v4
#     - name: Build
#       run: xcodebuild build -project Crave.xcodeproj -scheme Crave clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No


jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Install Dependencies
      run: |
        xcodebuild -resolvePackageDependencies
    
    - name: Build
      run: |
        xcodebuild clean build -scheme "${SCHEME_NAME}" \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest" \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
      env:
        SCHEME_NAME: Crave
    
    - name: Run Tests
      run: |
        xcodebuild test -scheme "${SCHEME_NAME}" \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest" \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
      env:
        SCHEME_NAME: Crave
